language: c
sudo: required
services:
  - docker

env:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

script:
  - docker build --build-arg tag=$OCAML_VERSION --tag colisanr/morbig:$TRAVIS_BRANCH .
  - docker run --entrypoint /bin/sh colisanr/morbig:$TRAVIS_BRANCH -c 'cd /home/opam/morbig && make check'

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  skip_cleanup: true
  script: docker push colisanr/morbig:$TRAVIS_BRANCH
  on:
    branch: master
    condition: $OCAML_VERSION = 4.04

matrix:
  include:
    - os: osx
      services: null
      env: null
      install:
        - brew install opam
        - opam init --no-setup
        - eval $(opam config env) && opam install --yes menhir yojson ppx_deriving_yojson visitors
      script:
        - make
        - make install
        - make uninstall
        - make check
