language: c
sudo: required
services:
  - docker

env:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

script:
  - docker build --build-arg tag=$OCAML_VERSION --tag colisanr/morbig .
  - docker run --entrypoint /bin/sh colisanr/morbig -c 'cd /home/opam/morbig && make check'

matrix:
  include:
    - os: osx
      services: null
      env: null
      install:
        - brew install opam
        - opam init --no-setup
        - eval $(opam config env) && opam install --yes menhir yojson ppx_deriving_yojson visitors
      script:
        - make
        - make install
        - make uninstall
        - make check
