language: c
sudo: required
install: sudo apt-get install ocaml aspcud
script: sh .travis.sh
os: linux
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.1
  - RUN_TESTS=yes OCAML_VERSION=4.06.0
